# matrix:
#   include:
#   - language: java
#     sudo: false
#     before_script:
#     - cd backend
#     script: mvn test -B
#   - language: node_js
#     before_install:
#     - cd frontend/javlet-app
#     node_js:
#     - '8'
#     cache:
#       directories:
#       - node_modules
#     before_script:
#     - npm update
#     install:
#     - npm install
#     script:
#     - npm test


# before_install:
# [START auth]
# - openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv -in client-secret.json.enc -out client-secret.json -d
# - gcloud auth activate-service-account --key-file client-secret.json
# [END auth]
# install:
# - gcloud config set project javets
# script:
# [START deploy]
# Deploy the app
before_install:
- cd frontend/javlet-app/
- openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv -in client-secret.json.enc -out client-secret.json -d
- gcloud auth activate-service-account --key-file client-secret.json
deploy:
  provider: gae
  keyfile: client-secret.json
  project: javets
  on:
    all_branches: true
# - gcloud -q app deploy
# [END deploy]


