matrix:
  include:
  
#Backend
  - language: java
    sudo: true
    before_install:
    - cd backend
    
    script: 
    - mvn test -B

#Frontend 
  - language: node_js
    services:
    - docker

    before_install:
    - cd frontend/javlet-app
    node_js:
    - '8'
    cache:
      directories:
      - node_modules
    before_script:
    - npm update
    install:
    - npm install
    script:
    - npm test
    - docker build -t javlet-frontend .
    deploy:
        provider: script
        script: bash docker_push
        on:
            branch: docker