matrix:
  include:
    - language: java
      sudo: false
      before_script:
        - cd backend
      script: mvn test -B

    - language: node_js
      before_install:
        - cd frontend/javlet-app
      node_js:
        - '8'
      cache:
        directories:
            - node_modules
      before_script:
        - npm update
      install:
        - npm install
      script:
        - npm test
        - npm run coveralls   