matrix:
  include:
  - language: java
    sudo: false
    before_script:
    - cd backend
    script: mvn test -B
  - language: node_js
    before_install:
    - cd frontend/javlet-app
    node_js:
    - '8'
    cache:
      directories:
      - node_modules
    before_script:
    - npm update
    install:
    - npm install
    script:
    - npm test

before_install:
- openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv
  -in client-secret.json.enc -out client-secret.json -d
