matrix:
  include:
  - language: java
    jdk: oraclejdk8
    # before_install:
    # - openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv -in client-secret.json.enc -out client-secret.json -d
    # - gcloud auth activate-service-account --key-file client-secret.json
    sudo: false
    before_script:
    - cd backend
    script: 
    - mvn test -B
    # - mvn appengine:deploy
  - language: node_js
    before_install:
    - openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv -in client-secret.json.enc -out client-secret.json -d
    - gcloud auth activate-service-account --key-file client-secret.json
    - cd frontend/javlet-app
    node_js:
    - '8'
    cache:
      directories:
      - node_modules
    before_script:
    - npm update
    install:
    - gcloud config set project javets
    - npm install
    script:
    - npm test
    - gcloud -q app deploy

# before_install:
# # [START auth]
# - openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv -in client-secret.json.enc -out client-secret.json -d
# - gcloud auth activate-service-account --key-file client-secret.json
# - cd frontend/javlet-app/
# # [END auth]
# install:
# - gcloud config set project javets
# - npm install
# script:
# - npm test
# - gcloud -q app deploy




# [START deploy]
# Deploy the app
# - openssl aes-256-cbc -K $encrypted_7cadf327361e_key -iv $encrypted_7cadf327361e_iv -in client-secret.json.enc -out client-secret.json -d
# - gcloud auth activate-service-account --key-file client-secret.json
# deploy:
#   provider: gae
#   keyfile: ../../client-secret.json
#   project: javets
#   on:
#     all_branches: true

# [END deploy]

