matrix:
  include:
    - language: java
    before_install:
        - chmod +x build.sh
      before_script:
        - cd backend

    - language: node_js
      before_script:
        - cd frontend/javlet-app
      node_js:
        - '8'
      cache:
        directories:
            - node_modules
      before_install:
        - npm update
      install:
        - npm install
      script:
        - npm test
        - npm run coveralls   